### ISSUE TITLE
[1.11.2]Server crash: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [ArtixAllMighty/Telepads2016#21]
```
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at subaraki.telepads.tileentity.TileEntityTelepad.func_73660_a(TileEntityTelepad.java:147)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Caused by: java.lang.NullPointerException
```
https://pastebin.com/jB0Ymqfz

**Comment by AbsolemJackdaw** [comment]
fixed this on the 21st of August

https://github.com/ArtixAllMighty/Telepads2016/commit/98b31546bda0f418f1542e7c0bd7a4cf93a217ef

are you usin the latest version ?

**Comment by AbsolemJackdaw** [comment]
closing issue as resolved due to lack of answer (which i see positively)
