### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CC2224-Cody** [ArtixAllMighty/Telepads2016#58]
[18Dec2021 20:23:25.697] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at subaraki.telepads.tileentity.TileEntityTelepad.func_189515_b(TileEntityTelepad.java:131) ~[telepads:1.16.5 - 3.0.0.3]
	at net.minecraft.item.BlockItem.func_179224_a(BlockItem.java:165) ~[?:?]
	at net.minecraft.item.BlockItem.func_195943_a(BlockItem.java:100) ~[?:?]
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:65) ~[?:?]
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644) ~[forge:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:186) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[18Dec2021 20:23:25.776] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ef87bbba-b462-4cab-91ea-75ec4f0cf84d
[18Dec2021 20:23:25.782] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at subaraki.telepads.tileentity.TileEntityTelepad.func_189515_b(TileEntityTelepad.java:131) ~[telepads:1.16.5 - 3.0.0.3]
	at subaraki.telepads.tileentity.TileEntityTelepad.func_189518_D_(TileEntityTelepad.java:75) ~[telepads:1.16.5 - 3.0.0.3]
	at net.minecraft.world.server.ChunkHolder.func_219305_a(ChunkHolder.java:217) ~[?:?]
	at net.minecraft.world.server.ChunkHolder.func_244385_a(ChunkHolder.java:209) ~[?:?]
	at net.minecraft.world.server.ChunkHolder.func_219274_a(ChunkHolder.java:189) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:355) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
[18Dec2021 20:23:26.210] [Server thread/ERROR] [net.minecraft.world.chunk.Chunk/]: A TileEntity type subaraki.telepads.tileentity.TileEntityTelepad has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: null
	at subaraki.telepads.tileentity.TileEntityTelepad.func_189515_b(TileEntityTelepad.java:131) ~[telepads:1.16.5 - 3.0.0.3]
	at net.minecraft.world.chunk.Chunk.func_223134_j(Chunk.java:427) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:287) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:687) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:337) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:312) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:698) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:532) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by AbsolemJackdaw** [comment]
any more detail ? list of mods ? steps to recreate ?

**Comment by AbsolemJackdaw** [comment]
This issue has been addressed. issue #59 had some more detail and I was able to fix it.
