### ISSUE TITLE
1.18 Server crashing

### ISSUE THREAD

**Issue by Wqery24** [ArtixAllMighty/Telepads2016#59]
Leaving my crash report here if it can help.
Single Player had no issues but on server it seems to trigger a crash a few different ways. If a player teleports an unloaded chunk and falls through the teleporter or any block it will trigger a server crash. World will not reload until the mod is removed and world saved without mod: If more info is needed I will do my best to provide it.

Time: 1/1/22, 6:59 PM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "this.dimension" is null
	at subaraki.telepads.tileentity.TileEntityTelepad.save(TileEntityTelepad.java:124) ~[telepads-1.18-5.0.0.0.jar%2340!:1.18-5.0.0.0] {re:classloading}
	at subaraki.telepads.tileentity.TileEntityTelepad.m_5995_(TileEntityTelepad.java:90) ~[telepads-1.18-5.0.0.0.jar%2340!:1.18-5.0.0.0] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading}
	at subaraki.telepads.tileentity.TileEntityTelepad.m_183216_(TileEntityTelepad.java:78) ~[telepads-1.18-5.0.0.0.jar%2340!:1.18-5.0.0.0] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2343!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

Running Mods:
cloth-config-6.1.48-forge
FallingTree-1.18.1-2.16.1
Inventory-Sorter-Mod-1.18.1
telepads-1.18-5.0.0.0
Xaeros_Minimap_21.22.6_Forge_1.18

**Comment by AbsolemJackdaw** [comment]
I will be looking into this thank you

**Comment by AbsolemJackdaw** [comment]
this issue has now been addressed and a new version will soon be up on curseforge.
Please come close the issue if the new version did effectively solve it.

**Comment by Wqery24** [comment]
The issue is cleared! The minor new issue is the top texture seems to be missing, also it cannot be destroyed in survival. These are disconnected issues. Thank you so much for the fast response!

**Comment by AbsolemJackdaw** [comment]
they can be destroyed in survival. i'd love for you to open a new issues with steps to follow.
the block has a strength of 5F, and needs a pickaxe to be mined
takes a second but it is possible
